name: chained

on:
  workflow_run:
    workflows:
      - main
    types:
      - completed

jobs:
  echo-context:
    runs-on: ubuntu-latest
    steps:
      - run: python workflow_run.py
        env:
          WORKFLOW_RUN: "${{ toJson(github.event.workflow_run) }}"
