name: "main"

on:
  push:
    branches:
      - main

jobs:
  create-artifacts:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name: ["hello", "world"]
    steps:
      - run: echo "${{ matrix.name }}" > ${{ matrix.name }}-name.txt
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: "${{ matrix.name }}-name"
          path: ${{ matrix.name}}-name.txt
